- hosts: all
  become: yes
  tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true
   
   - name: Build image
     community.docker.docker_image_build:
       name: dockerfile
       path: /Users/federico/desktop/vagrantm1/formazione_sou_k8s/JenkinsDocker
       dockerfile: dockerfile

   - name: Create container
     docker_container:
       name: container
       state: started
       image: dockerfile
       ports:
        - "8080:8080"
        - "50000:50000"
       volumes:
        - /var/run/docker.sock:/var/run/docker.sock





 