- hosts: all
  become: yes
  tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true
   
   - name: "Copy image in VM for build"
     ansible.builtin.template:
       src: /Users/federico/desktop/vagrantm1/formazione_sou_k8s/JenkinsDocker/Dockerfile
       dest: ./
       owner: vagrant
       group: vagrant
       mode: "0740"

   - name: "Build image"
     docker_image:
       name: dockerfile
       source: build
       build:
         path: ./
         dockerfile: Dockerfile

   - name: Create container
     docker_container:
       name: container
       state: started
       image: dockerfile
       ports:
        - "8080:8080"
        - "50000:50000"
       volumes:
        - /var/run/docker.sock:/var/run/docker.sock

   - name: Permission for docker socket
     ansible.builtin.shell:
       cmd: sudo -i docker exec -it --user root container bash -c 'cd /var/run && chgrp docker docker.sock'



 
